### ISSUE TITLE
Building fails when using whisper-rs, windows

### ISSUE THREAD

**Issue by stvn037** [tazz4843/whisper-rs#150]
Can anyone help me troubleshoot?
Running along with a python poetry app, 01 light, I get output below.
I first tried the steps in BUILDING.MD with the toolchain and MSYS2.
Is this related to the app or have I misconfigured rust/whisper-rs? any ideas?
```
   Compiling whisper-rs-sys v0.8.0
error: failed to run custom build command for `whisper-rs-sys v0.8.0`

Caused by:
  process didn't exit successfully: `C:\Users\usr0\AppData\Local\01\01\services\stt\local-whisper\whisper-rust\target\release\build\whisper-rs-sys-b4b17b6b38aab615\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=stdc++
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=./whisper.cpp\whisper.h
  cargo:rerun-if-changed=./whisper.cpp\ggml.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\vcruntime.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\sal.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\concurrencysal.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\vadefs.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\vadefs.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\__stddef_ptrdiff_t.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\__stddef_size_t.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\__stddef_wchar_t.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\__stddef_null.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\__stddef_max_align_t.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\__stddef_offsetof.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\stdbool.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\18\include\stdbool.h
  cargo:rerun-if-changed=./whisper.cpp\ggml.h
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-gnu = None
  CMAKE_GENERATOR_x86_64_pc_windows_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-gnu = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-gnu = None
  CMAKE_x86_64_pc_windows_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "-Wdev" "--debug-output" "C:\\Users\\usr0\\AppData\\Local\\01\\01\\services\\stt\\local-whisper\\whisper-rust\\target\\release\\build\\whisper-rs-sys-4fffbeea0fc5bb57\\out\\whisper.cpp/" "-G" "MinGW Makefiles" "-DBUILD_SHARED_LIBS=OFF" "-DWHISPER_ALL_WARNINGS=OFF" "-DWHISPER_ALL_WARNINGS_3RD_PARTY=OFF" "-DWHISPER_BUILD_TESTS=OFF" "-DWHISPER_BUILD_EXAMPLES=OFF" "-DWHISPER_METAL=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\usr0\\AppData\\Local\\01\\01\\services\\stt\\local-whisper\\whisper-rust\\target\\release\\build\\whisper-rs-sys-4fffbeea0fc5bb57\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"

  --- stderr
  thread 'main' panicked at C:\Users\usr0\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  failed to execute command: program not found
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-10 (run_until_complete):
Traceback (most recent call last):
  File "C:\Users\usr0\anaconda3\envs\03\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\usr0\anaconda3\envs\03\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\usr0\anaconda3\envs\03\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\usr0\03\01\software\source\server\server.py", line 470, in main
    service_instance = ServiceClass(config)
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr0\03\01\software\source\server\services\stt\local-whisper\stt.py", line 19, in __init__
    install(self.service_directory)
  File "C:\Users\usr0\03\01\software\source\server\services\stt\local-whisper\stt.py", line 54, in install
    subprocess.run(["cargo", "build", "--release"], check=True)
  File "C:\Users\usr0\anaconda3\envs\03\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'build', '--release']' returned non-zero exit status 101.
```

**Comment by tazz4843** [comment]
cmake doesn't appear to be installed, as you can see from the middle of the error message.

**Comment by tazz4843** [comment]
Closing, if this issue still persists feel free to reopen.
